### ISSUE TITLE
Allow NVDA+H to let us input text if nothing is on the clipboard.

### ISSUE THREAD

**Issue by blindndangerous** [SamKacer/HearthstoneCardLookup#1]
Would it be possible to let us input a cards name when pressing nvda+h instead of it defaulting to the clipboard?  Or, make it so that if the clipboard has text to autofill the search dialog but if not, leave it empty.

**Comment by SamKacer** [comment]
@blindndangerous hey, that's actually a great idea. I've found myself opening the windows search dialogue just to type in a name of a card, select it, and hit NVDA + H. So, this would simplify that quite a bit

Just so I completely understand you, right now when you press NVDA + H, it takes the card name from your text selection, if no text is selected, then it takes card name from clipboard. Your proposal is that it still takes card name from selection, but if nothing is selected, then it opens an input dialogue for the card name that is prepopulated with contents of clipboard if available?

**Comment by SamKacer** [comment]
Introduced new gesture/command in v0.5 to implement this feature
